import { useState, useEffect, useRef } from 'react';
import { X, Minus, Maximize2, Sparkles, Loader2, ChevronRight, Check } from 'lucide-react';
import { callEdgeFunction } from '../lib/edgeFunctions';

interface AIHelperPanelProps {
  isOpen: boolean;
  onClose: () => void;
  fieldName: string;
  fieldDescription?: string;
  currentValue: string;
  courseTopic?: string;
  onInsert: (content: string) => void;
}

interface Message {
  role: 'assistant' | 'user';
  content: string;
}

interface ParsedOption {
  text: string;
  cleanText: string;
}

const parseOptions = (content: string): ParsedOption[] | null => {
  const lines = content.split('\n').filter(line => line.trim());

  const numberedPattern = /^(\d+[\.)]\s*)/;
  const bulletPattern = /^([-*•]\s*)/;
  const markedPattern = /^(\*\*\d+[\.)]\s*\*\*)/;

  const potentialOptions = lines.filter(line => {
    const trimmed = line.trim();

    // Skip character count lines like "(67 characters)*"
    if (/^\(\d+\s*characters?\)\*?$/i.test(trimmed)) {
      return false;
    }

    // Skip lines that are just labels like "*Value Proposition 1:" or "Option 1:"
    if (/^[*\s]*(?:Value Proposition|Option|Title|Description)\s*\d*\s*:?\s*$/i.test(trimmed)) {
      return false;
    }

    // Check if line starts with number, bullet, or markdown
    const hasMarker = numberedPattern.test(trimmed) || bulletPattern.test(trimmed) || markedPattern.test(trimmed);
    if (!hasMarker) {
      return false;
    }

    // Remove markers to check content length
    let contentOnly = trimmed.replace(/^(\d+[\.)]\s*)/, '');
    contentOnly = contentOnly.replace(/^([-*•]\s*)/, '');
    contentOnly = contentOnly.replace(/^(\*\*\d+[\.)]\s*\*\*)/, '');
    contentOnly = contentOnly.replace(/\*\*/g, '').trim();

    // Only include if there's substantial content (more than just a label)
    return contentOnly.length > 10;
  });

  if (potentialOptions.length >= 2) {
    return potentialOptions.map(option => {
      let cleanText = option.trim();
      cleanText = cleanText.replace(/^(\d+[\.)]\s*)/, '');
      cleanText = cleanText.replace(/^([-*•]\s*)/, '');
      cleanText = cleanText.replace(/^(\*\*\d+[\.)]\s*\*\*)/, '');
      cleanText = cleanText.replace(/\*\*/g, '');
      cleanText = cleanText.trim();

      return {
        text: option.trim(),
        cleanText: cleanText
      };
    });
  }

  return null;
};

export default function AIHelperPanel({
  isOpen,
  onClose,
  fieldName,
  fieldDescription,
  currentValue,
  courseTopic,
  onInsert,
}: AIHelperPanelProps) {
  const [isMinimized, setIsMinimized] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [customPrompt, setCustomPrompt] = useState('');
  const [selectedOptions, setSelectedOptions] = useState<Record<number, number>>({});
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const hasAutoGenerated = useRef(false);

  const starterChips = [
    "Give me 5 headline ideas",
    "Rewrite this to sound more exciting",
    "Make this kid-friendly",
    "Make this more professional",
  ];

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  useEffect(() => {
    if (isOpen && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleAutoGenerate();
    }
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) {
      setMessages([]);
      setCustomPrompt('');
      setSelectedOptions({});
      hasAutoGenerated.current = false;
    }
  }, [isOpen]);

  const handleAutoGenerate = async () => {
    setIsLoading(true);
    try {
      console.log('Calling AI assistant with:', {
        fieldName,
        fieldDescription,
        currentValue,
        courseTopic,
        action: 'generate',
      });

      const response = await callEdgeFunction('landing-page-assistant', {
        fieldName,
        fieldDescription,
        currentValue,
        courseTopic,
        action: 'generate',
      });

      console.log('AI assistant response:', response);

      if (response.success) {
        setMessages([{ role: 'assistant', content: response.content }]);
      } else {
        const errorMessage = response.error || 'Sorry, I encountered an error. Please try again.';
        console.error('AI assistant returned error:', errorMessage);
        setMessages([
          {
            role: 'assistant',
            content: errorMessage,
          },
        ]);
      }
    } catch (error: any) {
      console.error('Error calling AI assistant:', error);
      const errorMessage = error?.message || 'Sorry, I encountered an error. Please try again.';
      setMessages([
        {
          role: 'assistant',
          content: `Error: ${errorMessage}`,
        },
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSendPrompt = async (prompt: string) => {
    if (!prompt.trim()) return;

    setMessages((prev) => [...prev, { role: 'user', content: prompt }]);
    setCustomPrompt('');
    setIsLoading(true);

    try {
      const response = await callEdgeFunction('landing-page-assistant', {
        fieldName,
        fieldDescription,
        currentValue,
        courseTopic,
        action: 'generate',
        customPrompt: prompt,
      });

      if (response.success) {
        setMessages((prev) => [...prev, { role: 'assistant', content: response.content }]);
      } else {
        const errorMessage = response.error || 'Sorry, I encountered an error. Please try again.';
        console.error('AI assistant returned error:', errorMessage);
        setMessages((prev) => [
          ...prev,
          {
            role: 'assistant',
            content: errorMessage,
          },
        ]);
      }
    } catch (error: any) {
      console.error('Error calling AI assistant:', error);
      const errorMessage = error?.message || 'Sorry, I encountered an error. Please try again.';
      setMessages((prev) => [
        ...prev,
        {
          role: 'assistant',
          content: `Error: ${errorMessage}`,
        },
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleTryAnother = async () => {
    setIsLoading(true);
    try {
      const response = await callEdgeFunction('landing-page-assistant', {
        fieldName,
        fieldDescription,
        currentValue,
        courseTopic,
        action: 'regenerate',
      });

      if (response.success) {
        setMessages((prev) => [...prev, { role: 'assistant', content: response.content }]);
      }
    } catch (error) {
      console.error('Error regenerating:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleRefine = async (content: string) => {
    setIsLoading(true);
    try {
      const response = await callEdgeFunction('landing-page-assistant', {
        fieldName,
        fieldDescription,
        currentValue: content,
        courseTopic,
        action: 'refine',
      });

      if (response.success) {
        setMessages((prev) => [...prev, { role: 'assistant', content: response.content }]);
      }
    } catch (error) {
      console.error('Error refining:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleInsertContent = (content: string, messageIndex: number) => {
    const options = parseOptions(content);

    if (options && selectedOptions[messageIndex] !== undefined) {
      onInsert(options[selectedOptions[messageIndex]].cleanText);
    } else {
      onInsert(content);
    }
  };

  const handleSelectOption = (messageIndex: number, optionIndex: number) => {
    setSelectedOptions(prev => ({
      ...prev,
      [messageIndex]: optionIndex
    }));
  };

  if (!isOpen) return null;

  return (
    <>
      <div
        className="fixed inset-0 bg-black bg-opacity-20 z-40 transition-opacity"
        onClick={onClose}
      />

      <div
        className={`fixed right-0 top-0 h-full bg-white shadow-2xl z-50 transform transition-all duration-300 ease-in-out ${
          isMinimized ? 'w-16' : 'w-full md:w-[420px]'
        }`}
      >
        {isMinimized ? (
          <div className="h-full flex flex-col items-center justify-center">
            <button
              onClick={() => setIsMinimized(false)}
              className="p-3 hover:bg-slate-100 rounded-lg transition-colors"
              title="Restore panel"
            >
              <Maximize2 className="w-5 h-5 text-slate-600" />
            </button>
            <button
              onClick={onClose}
              className="p-3 hover:bg-slate-100 rounded-lg transition-colors mt-4"
              title="Close panel"
            >
              <X className="w-5 h-5 text-slate-600" />
            </button>
          </div>
        ) : (
          <div className="h-full flex flex-col">
            <div className="bg-gradient-to-r from-blue-600 to-blue-700 text-white p-4 flex items-center justify-between shadow-md">
              <div className="flex items-center gap-2">
                <Sparkles className="w-5 h-5" />
                <div>
                  <h3 className="font-bold text-lg">AI Writing Assistant</h3>
                  <p className="text-xs text-blue-100">{fieldName}</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setIsMinimized(true)}
                  className="p-2 hover:bg-blue-500 rounded-lg transition-colors"
                  title="Minimize"
                >
                  <Minus className="w-4 h-4" />
                </button>
                <button
                  onClick={onClose}
                  className="p-2 hover:bg-blue-500 rounded-lg transition-colors"
                  title="Close"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {messages.length === 0 && !isLoading && (
                <div className="space-y-4">
                  <p className="text-slate-600 text-center py-8">
                    What would you like help writing?
                  </p>
                  <div className="space-y-2">
                    {starterChips.map((chip, idx) => (
                      <button
                        key={idx}
                        onClick={() => handleSendPrompt(chip)}
                        className="w-full px-4 py-3 bg-slate-100 hover:bg-blue-50 hover:border-blue-300 text-slate-700 hover:text-blue-700 rounded-lg transition-colors text-left border-2 border-slate-200 flex items-center justify-between group"
                      >
                        <span className="text-sm font-medium">{chip}</span>
                        <ChevronRight className="w-4 h-4 opacity-0 group-hover:opacity-100 transition-opacity" />
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {messages.map((message, idx) => {
                const options = message.role === 'assistant' ? parseOptions(message.content) : null;
                const selectedOptionIndex = selectedOptions[idx];
                const hasOptions = options && options.length > 0;

                return (
                  <div key={idx} className="space-y-3">
                    {message.role === 'user' ? (
                      <div className="bg-blue-50 rounded-lg p-3 border border-blue-200">
                        <p className="text-sm text-blue-900">{message.content}</p>
                      </div>
                    ) : (
                      <div className="space-y-3">
                        {hasOptions ? (
                          <>
                            <div className="bg-blue-50 rounded-lg p-3 border border-blue-200">
                              <p className="text-xs font-medium text-blue-900">
                                Select one option below:
                              </p>
                            </div>
                            <div className="space-y-2">
                              {options.map((option, optionIdx) => (
                                <button
                                  key={optionIdx}
                                  onClick={() => handleSelectOption(idx, optionIdx)}
                                  className={`w-full p-3 rounded-lg border-2 transition-all text-left group ${
                                    selectedOptionIndex === optionIdx
                                      ? 'border-blue-600 bg-blue-50'
                                      : 'border-slate-200 bg-white hover:border-blue-300 hover:bg-blue-50'
                                  }`}
                                >
                                  <div className="flex items-start gap-3">
                                    <div
                                      className={`flex-shrink-0 w-5 h-5 rounded-full border-2 flex items-center justify-center transition-all ${
                                        selectedOptionIndex === optionIdx
                                          ? 'border-blue-600 bg-blue-600'
                                          : 'border-slate-300 group-hover:border-blue-400'
                                      }`}
                                    >
                                      {selectedOptionIndex === optionIdx && (
                                        <Check className="w-3 h-3 text-white" />
                                      )}
                                    </div>
                                    <p className="text-sm text-slate-800 flex-1 leading-relaxed">
                                      {option.cleanText}
                                    </p>
                                  </div>
                                </button>
                              ))}
                            </div>
                          </>
                        ) : (
                          <div className="bg-slate-50 rounded-lg p-4 border border-slate-200">
                            <p className="text-sm text-slate-800 whitespace-pre-wrap leading-relaxed mb-3">
                              {message.content}
                            </p>
                          </div>
                        )}
                        <div className="flex flex-wrap gap-2">
                          <button
                            onClick={() => handleInsertContent(message.content, idx)}
                            disabled={hasOptions && selectedOptionIndex === undefined}
                            className="px-3 py-1.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed"
                            title={hasOptions && selectedOptionIndex === undefined ? 'Please select an option first' : ''}
                          >
                            Insert into field
                          </button>
                          <button
                            onClick={handleTryAnother}
                            disabled={isLoading}
                            className="px-3 py-1.5 bg-slate-200 text-slate-700 rounded-lg hover:bg-slate-300 transition-colors text-sm font-medium disabled:opacity-50"
                          >
                            Try another
                          </button>
                          <button
                            onClick={() => handleRefine(message.content)}
                            disabled={isLoading}
                            className="px-3 py-1.5 bg-slate-200 text-slate-700 rounded-lg hover:bg-slate-300 transition-colors text-sm font-medium disabled:opacity-50"
                          >
                            Refine this
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}

              {isLoading && (
                <div className="flex items-center gap-2 text-slate-500 bg-slate-50 rounded-lg p-4">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span className="text-sm">Thinking...</span>
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>

            <div className="border-t border-slate-200 p-4">
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  handleSendPrompt(customPrompt);
                }}
                className="flex gap-2"
              >
                <input
                  type="text"
                  value={customPrompt}
                  onChange={(e) => setCustomPrompt(e.target.value)}
                  placeholder="Ask for something specific..."
                  className="flex-1 px-4 py-2 border-2 border-slate-200 rounded-lg focus:border-blue-600 focus:outline-none text-sm"
                  disabled={isLoading}
                />
                <button
                  type="submit"
                  disabled={!customPrompt.trim() || isLoading}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed text-sm"
                >
                  Ask
                </button>
              </form>
            </div>
          </div>
        )}
      </div>
    </>
  );
}
