/*
  # Add Quiz Editing and AI Generation Support

  1. Changes to Existing Tables
    - Add `is_ai_generated` to quiz_questions table to track which questions were AI-generated vs manually added
    - Add `generation_parameters` to quizzes table to store the settings used for AI generation
    - Add `last_edited_at` to quiz_questions for tracking edits
    - Add `edited_by` to quiz_questions for tracking who edited the question
    - Add `version` to quiz_questions for tracking edit history

  2. New Columns
    - `is_ai_generated` (boolean) - indicates if question was generated by AI
    - `generation_parameters` (jsonb) - stores settings like difficulty mix, questions per lesson, etc.
    - `last_edited_at` (timestamptz) - when question was last edited
    - `edited_by` (uuid) - user who last edited the question
    - `version` (integer) - increments with each edit

  3. Security
    - Update RLS policies to handle new fields
    - Ensure users can only edit questions for their own courses
*/

-- Add columns to quiz_questions table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'quiz_questions' AND column_name = 'is_ai_generated'
  ) THEN
    ALTER TABLE quiz_questions ADD COLUMN is_ai_generated boolean DEFAULT true;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'quiz_questions' AND column_name = 'last_edited_at'
  ) THEN
    ALTER TABLE quiz_questions ADD COLUMN last_edited_at timestamptz;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'quiz_questions' AND column_name = 'edited_by'
  ) THEN
    ALTER TABLE quiz_questions ADD COLUMN edited_by uuid REFERENCES auth.users(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'quiz_questions' AND column_name = 'version'
  ) THEN
    ALTER TABLE quiz_questions ADD COLUMN version integer DEFAULT 1;
  END IF;
END $$;

-- Add generation_parameters to quizzes table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'quizzes' AND column_name = 'generation_parameters'
  ) THEN
    ALTER TABLE quizzes ADD COLUMN generation_parameters jsonb DEFAULT '{}'::jsonb;
  END IF;
END $$;

-- Create index for efficient filtering of AI-generated questions
CREATE INDEX IF NOT EXISTS idx_quiz_questions_is_ai_generated ON quiz_questions(is_ai_generated);

-- Create index for edited_by lookups
CREATE INDEX IF NOT EXISTS idx_quiz_questions_edited_by ON quiz_questions(edited_by);

-- Update timestamp function for quiz_questions
CREATE OR REPLACE FUNCTION update_quiz_question_modified()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  IF OLD.question_text != NEW.question_text OR 
     OLD.options != NEW.options OR 
     OLD.correct_answer != NEW.correct_answer OR 
     OLD.explanation != NEW.explanation THEN
    NEW.version = OLD.version + 1;
    NEW.last_edited_at = now();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS trigger_update_quiz_question_modified ON quiz_questions;

-- Create trigger for automatic timestamp and version updates
CREATE TRIGGER trigger_update_quiz_question_modified
  BEFORE UPDATE ON quiz_questions
  FOR EACH ROW
  EXECUTE FUNCTION update_quiz_question_modified();
