/*
  # Fix Course Status Constraint and Update Logic
  
  1. Changes
    - Drop existing status check constraint that was too restrictive
    - Add new constraint that includes 'draft' status (matching the default value)
    - Ensure courses can transition between all valid statuses
  
  2. Valid Status Values
    - 'draft' - Initial state when course is created
    - 'generating' - Course content is being generated by AI
    - 'completed' - Course generation completed successfully
    - 'failed' - Course generation failed
    - 'ready_for_quizzes' - Course is ready for quiz generation
  
  3. Why This Fixes the Update Issue
    - Previous constraint didn't include 'draft' but default was 'draft'
    - This caused constraint violations when trying to update courses
    - Now all status transitions are properly supported
*/

-- Drop the old constraint
ALTER TABLE courses DROP CONSTRAINT IF EXISTS courses_status_check;

-- Add the corrected constraint with all valid statuses including 'draft'
ALTER TABLE courses ADD CONSTRAINT courses_status_check 
  CHECK (status IN ('draft', 'generating', 'completed', 'failed', 'ready_for_quizzes'));